### ISSUE TITLE
Cette chaine ne répond pas

### ISSUE THREAD

**Issue by ninuxio** [tuxity/MYTF1.bundle#2]
Hi,

i can browse all shows but when i need to display any episode i have an error "Cette chaine ne répond pas" 

i'm up to date with my  PMS version.

where i can find logs to complete this issue ?

regards

**Comment by tuxity** [comment]
Should be fixed in https://github.com/tuxity/MYTF1.bundle/commit/f1a63b6b99c62e5b8981d8b00e57e70c1ffd9283 and I've released version 1.1.0. Thanks for your report 👍

**Comment by ninuxio** [comment]
hi, it's working for me on my mac thanks
