### ISSUE TITLE
Cette extension ne répond pas.

### ISSUE THREAD

**Issue by AlexisWalravens** [tuxity/MYTF1.bundle#4]
Hello,  
Je pense que l'extension ne fonctionne plus correctement, suite à un changement sur le site de TF1.
Je peux toujours naviguer dans les vidéos mais une fois que l'on clique sur une vidéo pour la regarder, j'obtiens le message suivant: "Cette extension ne répond pas."

Et sur mon Apple TV il ne ne se passe tout simplement rien.

Merci.

**Comment by tuxity** [comment]
Salut! Je n'ai pas utilisé l'extension depuis jeudi, je vais regarder ca ;)

EDIT: Je viens tester sur ma NVIDIA SHIELD et sur navigateur, et pas de problemes. Peux-tu reessayer ? Vider le cache, et checker les logs de Plex Media Server

**Comment by AlexisWalravens** [comment]
Rebonsoir,

Bon finalement j'ai arrêté et relancé le serveur et ça refonctionne. :)
Je ne sais même pas pourquoi je n'ai pas pensé à faire ça avant de poster un issue..

En tout cas merci, c'est cool de voir que tu es réactif. :D
