### ISSUE TITLE
Cette extension ne répond pas

### ISSUE THREAD

**Issue by Siiriion** [tuxity/MYTF1.bundle#6]
Bonjour,

actuellement en version 3.44.1 le plug-in est bien détecté, mais lorsque je clic dessus dans l'interface serveur de Plex, j'ai le message d'erreur : Cette extension ne répond pas.
J'ai redémarré le serveur plusieurs fois sans changement.

Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch

Merci pour votre aide.

**Comment by tuxity** [comment]
Bonjour,

c'est lié a #5, tf1 force depuis peu a passer par du https et Plex a arreté le support des plugins donc la lib interne n'est pas a jour...
